import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
await page.goto('http://localhost:4206', { waitUntil: 'domcontentloaded' });
const headPos = async () => page.evaluate(() => {
  const d = window.__orbitalVerification?.getLastDrawables?.() ?? [];
  const head = d.find(x => x.fill === '#4ade80');
  return head ? { x: head.position.x, y: head.position.y, n: d.length } : null;
});
await page.waitForTimeout(700);
console.log('t0', JSON.stringify(await headPos()));
await page.keyboard.press('ArrowDown');
await page.waitForTimeout(700);
console.log('after DOWN (y should grow):', JSON.stringify(await headPos()));
await page.keyboard.press('ArrowLeft');
await page.waitForTimeout(700);
console.log('after LEFT (x should shrink):', JSON.stringify(await headPos()));
await page.screenshot({ path: '/tmp/snake-steer2.png' });
await browser.close();
